src/Entity/Task.php
<?php

namespace App\Entity;

use App\Repository\TaskRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TaskRepository::class)]
class Task
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $content = null;

    #[ORM\Column(nullable: true)]
    private ?bool $is_done = null;

    #[ORM\ManyToOne(inversedBy: 'tasks')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $author = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function isIsDone(): ?bool
    {
        return $this->is_done;
    }

    public function setIsDone(?bool $is_done): self
    {
        $this->is_done = $is_done;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }
}

src/Controller/TaskController.php
<?php

namespace App\Controller;

use App\Entity\Task;
use \DateTimeImmutable;
use App\Form\TaskFormType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Doctrine\Persistence\ManagerRegistry;

#[Route('/task')]
class TaskController extends AbstractController
{

    #[Route('/create', name: 'create_task')]
    #[IsGranted('IS_AUTHENTICATED')]
    public function create(Request $request, ManagerRegistry $doctrine): Response
    {
        $task = new Task();
        $entityManager = $doctrine->getManager();
        $form = $this->createForm(TaskFormType::class, $task);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $now = new DateTimeImmutable();
            $task = $form->getData();
            $task->setIsDone(false);
            $task->setCreatedAt($now);
            $task->setUpdatedAt($now);
            $task->setAuthor($user = $this->getUser());
            $entityManager->persist($task);
            $entityManager->flush();
            $this->addFlash('success', 'La tâche a bien été ajoutée.');
            return $this->redirectToRoute('list_task');
        }

        return $this->render('task/form.html.twig', [
            'taskForm' => $form,
            'action' => 'create',
        ]);
    }

    #[Route('/list', name: 'list_task')]
    #[IsGranted('IS_AUTHENTICATED')]
    public function list(ManagerRegistry $doctrine): Response
    {
        $entityManager = $doctrine->getManager();
        $tasks = $entityManager->getRepository(Task::class)->findAll();
        return $this->render('task/list.html.twig', [
            'tasks' => $tasks,
        ]);
    }

    #[Route('/update/{taskId}', name: 'update_task')]
    #[IsGranted('IS_AUTHENTICATED')]
    public function update(
        Request $request,
        ManagerRegistry $doctrine,
        int $taskId = 0
    ): Response {
        $entityManager = $doctrine->getManager();
        $task = $entityManager->getRepository(Task::class)->find($taskId);
        $form = $this->createForm(TaskFormType::class, $task);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $now = new DateTimeImmutable();
            $task->setUpdatedAt($now);
            $entityManager->flush();
            $this->addFlash('success', 'La tâche a bien été mise à jour.');
            return $this->redirectToRoute('list_task');
        }

        return $this->render('task/form.html.twig', [
            'taskForm' => $form,
            'action' => 'update',
        ]);
    }

    #[Route('/status/{taskId}/{taskStatus}', name: 'status_task')]
    #[IsGranted('IS_AUTHENTICATED')]
    public function updateStatus(
        ManagerRegistry $doctrine,
        int $taskId,
        int $taskStatus
    ): Response {
        $entityManager = $doctrine->getManager();
        $task = $entityManager->getRepository(Task::class)->find($taskId);
        $taskStatus = ($taskStatus === 1 ? true : false);
        $task->setIsDone($taskStatus);
        $now = new DateTimeImmutable();
        $task->setUpdatedAt($now);
        $entityManager->flush();
        if ($taskStatus === true) {
            $this->addFlash('success', 'La tâche ' . $task->getTitle() . ' a bien été marquée comme faite.');
        } else {
            $this->addFlash('success', 'La tâche ' . $task->getTitle() . ' a bien été marquée comme à faire.');
        }
        return $this->redirectToRoute('list_task');
    }

    #[Route('/delete/{taskId}', name: 'delete_task')]
    #[IsGranted('IS_AUTHENTICATED')]
    public function delete(
        Request $request,
        ManagerRegistry $doctrine,
        int $taskId
    ): Response {
        $entityManager = $doctrine->getManager();
        $task = $entityManager->getRepository(Task::class)->find($taskId);
        $entityManager->remove($task);
        $entityManager->flush();
        $this->addFlash('success', 'La tâche a bien été supprimée.');
        return $this->redirectToRoute('list_task');
    }
}

templates/task/form.html.twig
{% extends 'base.html.twig' %}

{% block title %}
{% if action == 'create' %}
ToDo & Co - Create task
{% else %}
ToDo & Co - Update task
{% endif %}
{% endblock %}

{% block body %}
<div class="d-flex justify-content-center">
  <img src="{{ asset('images/banner.png') }}" class="todo_image" alt="">
</div>

<div class="mt-4">
  {{ form_start(taskForm) }}
  {% if action == 'create' %}
  <h1 class="bold-txt-med">Créer une tâche</h1>
  {% else %}
  <h1 class="bold-txt-med">Modifier une tâche</h1>
  {% endif %}
  <div class="d-flex flex-column justify-content-center">
    <div class="mt-4 bold-txt-med">
      {{ form_label(taskForm.title, 'Titre') }}
      {{ form_row(taskForm.title, {'attr': {'class': 'task_input'}}) }}
    </div>
    <div class="mt-4 bold-txt-med">
      {{ form_label(taskForm.content, 'Détail') }}
      {{ form_row(taskForm.content, {'attr': {'class': 'task_input'}}) }}
    </div>
    <div class="mt-4 d-flex" id="register_submit_div">
      {% if action == 'create' %}
      <button type="submit" class="btn btn-success">Ajouter</button>
      {% else %}
      <button type="submit" class="btn btn-success">Modifier</button>
      {% endif %}
    </div>
  </div>
  {{ form_end(taskForm) }}

</div>

{% endblock %}

templates/task/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}ToDo & Co - Task list{% endblock %}

{% block body %}

<div class="d-flex justify-content-center">
  <img src="{{ asset('images/banner.png') }}" class="todo_image" alt="">
</div>

<div class="container mt-4">
  <h1 class="bold-txt-med">Liste des tâches</h1>
  <div class="mb-4">
    <a class="btn btn-success" href="{{ path('create_task') }}" role="button">Créer une nouvelle tâche</a>
  </div>

  {% for task in tasks %}
  {% if loop.index == 1 or (loop.index-1)%3 == 0 %}
  <div class="row justify-content-center task_row">
    {% endif %}
    <div class="col-sm mb-4">
      <div class="card mb-1" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title d-flex justify-content-between">
            <a class="task_title" href="{{ path('update_task', { 'taskId': task.id}) }}">{{ task.title }}</a>
            {% if task.isDone == true %}
            <span class="task_status_symbol task_done_symbol">&#10003;</span>
            {% else %}
            <span class="task_status_symbol task_undone_symbol">X</span>
            {% endif %}
          </h5>
          <p class="card-text">{{ task.content }}</p>
        </div>
      </div>
      {% if is_granted('ROLE_ADMIN') or app.user.id == task.author.id %}
      <a class="btn btn-danger" href="{{ path('delete_task', { 'taskId': task.id}) }}" role="button">Supprimer</a>
      {% endif %}

      {% if task.isDone == true %}
      <a class="btn btn-success" href="{{ path('status_task', { 'taskId': task.id, 'taskStatus': 0 }) }}" role="button">Marquer non terminée</a>
      {% else %}
      <a class="btn btn-success" href="{{ path('status_task', { 'taskId': task.id, 'taskStatus': 1 }) }}" role="button">Marquer comme
        faite</a>
      {% endif %}

    </div>
    {% if loop.index%3 == 0 %}
  </div>
  {% endif %}
  {% endfor %}

</div>

{% endblock %}